services:
  skipper-backend:
    image: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      service-db:
        condition: service_started
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://service-db:3307/TinkoffProjectDatabase?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456

  service-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: TinkoffProjectDatabase
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
